<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gallery extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $data = $this->session->userdata('logged_in');
        $status = $data['level'];
        if (! $this->acl->is_public('gallery'))
        {
            if (! $this->acl->is_allowed('gallery', $status))
            {
                redirect('auth/logout_action','refresh');
            }
        }
        $this->load->model('Gallery_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
    }

    public function index()
    {
        $this->load->view('gallery/gallery_list');
    }
    
    public function detailGalery($id){
        $data = array(
            'gallery' => $this->Gallery_model->get_by_spot($id), 
            'id_params' => $id,
        );
        $this->render['content']= $this->load->view('gallery/gallery_read', $data, TRUE);
        $this->load->view('template', $this->render);
    }
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Gallery_model->json();
    }

    public function create($params) 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('gallery/create_action'),
	        'image' => set_value('image'),
	        'spot_id' => set_value('spot_id',$params),
        );
        $this->render['content']= $this->load->view('gallery/gallery_form', $data, TRUE);
        $this->load->view('template', $this->render);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create($this->input->post('spot_id',TRUE));
        } else {
            $config['upload_path']          = './assets/upload/product/';
            $config['allowed_types']        = 'gif|jpg|png|jpeg';
            $config['max_size']             = 1000000000;
            $config['max_width']            = 10240;
            $config['max_height']           = 7680;
            
            $this->load->library('upload', $config);

            if ( !$this->upload->do_upload('image')){
                $error = array('error' => $this->upload->display_errors());
                var_dump($error);
            }else{
                $file = 'assets/upload/product/'.$this->upload->data('file_name');
                $data = array(
                    'image' => $file,
                    'type_gallery_id' => $this->input->post('type_gallery',TRUE),
                    'spot_id' => $this->input->post('spot_id',TRUE),
                );
                $this->Gallery_model->insert($data);
                $this->session->set_flashdata('message', 'Create Record Success');
                redirect(site_url('gallery/detailGalery/'.$this->input->post('spot_id',TRUE)));
            }
        }
    }
    
    public function delete($id,$param) 
    {
        $row = $this->Gallery_model->get_by_id($id);

        if ($row) {
            $this->Gallery_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('gallery/detailGalery/'.$param));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('gallery/detailGalery/'.$param));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('spot_id', 'spot id', 'trim|required');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Gallery.php */
/* Location: ./application/controllers/Gallery.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-22 05:40:35 */
/* http://harviacode.com */