<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Event_model extends CI_Model
{

    public $table = 'event';
    public $id = 'event.id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('event.id,event.name,event.date,event.location,event.description,event.image,user.name as userName,spot.name as spotName,event.price');
        $this->datatables->from('event');
        //add this line for join
        $this->datatables->join('spot', 'event.spot_id = spot.id');
        $this->datatables->join('user', 'event.user_id = user.id');
        $this->datatables->add_column('action', anchor(site_url('event/read/$1'),'Read')." | ".anchor(site_url('event/update/$1'),'Update')." | ".anchor(site_url('event/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->select('event.id,event.name,event.date,event.location,event.description,event.image,user.name as userName,spot.name as spotName,event.price');
        $this->datatables->join('spot', 'event.spot_id = spot.id');
        $this->datatables->join('user', 'event.user_id = user.id');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_all_limit($limit, $start){
        $this->db->select('event.id,event.name,event.date,event.location,event.description,event.image,user.name as userName,spot.name as spotName,event.price');
        $this->datatables->join('spot', 'event.spot_id = spot.id');
        $this->datatables->join('user', 'event.user_id = user.id');
        $this->db->order_by($this->id, $this->order);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->datatables->select('event.id,event.name,event.date,event.location,event.description,event.image,user.name as userName,spot.name as spotName,event.price');
        $this->db->where($this->id, $id);
        $this->db->join('spot', 'event.spot_id = spot.id');
        $this->db->join('user', 'event.user_id = user.id');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('date', $q);
	$this->db->or_like('location', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('user_id', $q);
    $this->db->or_like('spot_id', $q);
    $this->db->or_like('price', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('date', $q);
	$this->db->or_like('location', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('image', $q);
	$this->db->or_like('user_id', $q);
    $this->db->or_like('spot_id', $q);
    $this->db->or_like('price', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Event_model.php */
/* Location: ./application/models/Event_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-03-29 14:45:53 */
/* http://harviacode.com */